### PR TITLE
add README with installation instructions

### PR DESCRIPTION
**Pull request by s-ol**

### CODE REVIEW

**Comment by hishamhm** [comment]
@s-ol Thank you for the first PR in the project's history! :)

**Comment by s-ol** [comment]
happy to witness :slightly_smiling_face:

I came here via link from the [future of coding slack](https://futureofcoding.org/) by the way, if you hadn't heard of it.

**Comment by akavel** [comment]
Hm, I just don't understand, what does rust have to do with it? 🙄 I don't seem to see any .rs files in the userland repo?? 😳

**Comment by s-ol** [comment]
@akavel: the syntax highlighter used is  implemented in rust and needs to be compiled to be available in Lua. This is done by luarocks. You can find the project here: https://github.com/hishamhm/lua-syntect

**Comment by akavel** [comment]
@s-ol cool, thanks for the explanation! :)

**Pull request merged**
